spring:
  application:
    name: example
  config:
    import: configserver:http://localhost:8888
  profiles:
    active: prod

server:
  port: 9093

management:
  endpoints:
    web:
      exposure:
        include: "*" #['refresh', 'beans', 'env', 'info']
